/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package Vistas;

/**
 *
 * @author Juan
 */
public class Dia_De_Spa extends javax.swing.JInternalFrame {

    /** Creates new form Dia_De_Spa */
    public Dia_De_Spa() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSesiones = new javax.swing.JTable();
        jLTITULO = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLCliente = new javax.swing.JLabel();
        jLPrefe = new javax.swing.JLabel();
        jLCP = new javax.swing.JLabel();
        jLMonto = new javax.swing.JLabel();
        jLSUBTITULO = new javax.swing.JLabel();
        jCBCliente = new javax.swing.JComboBox<>();
        jTFFecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTXTAREAPREF = new javax.swing.JTextArea();
        jTFCodPack = new javax.swing.JTextField();
        jTFTotal = new javax.swing.JTextField();
        jBtnNewdia = new javax.swing.JButton();
        jBtnGuardarDia = new javax.swing.JButton();
        jBtnEliminarDia = new javax.swing.JButton();
        jBtnListarDias = new javax.swing.JButton();
        jBtnVerSesiones = new javax.swing.JButton();
        jBtnActualizarTabla = new javax.swing.JButton();
        jBtnEliminarSesion = new javax.swing.JButton();

        jTableSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Hora Ini", "Hora Fin", "Masajista", "Consul.", "Tratam.", "Insta."
            }
        ));
        jScrollPane1.setViewportView(jTableSesiones);

        jLTITULO.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLTITULO.setForeground(new java.awt.Color(0, 0, 0));
        jLTITULO.setText("Gestion Día de Spa");

        jLFecha.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLFecha.setText("Fecha:");

        jLCliente.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLCliente.setText("Cliente:");

        jLPrefe.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLPrefe.setText("Preferencias:");

        jLCP.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLCP.setText("CodPack:");

        jLMonto.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLMonto.setText("Monto Total:");

        jLSUBTITULO.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLSUBTITULO.setForeground(new java.awt.Color(0, 0, 0));
        jLSUBTITULO.setText("Sesiones Vinculadas al Día de Spa");

        jCBCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTFFecha.setText("jTextField1");

        jTXTAREAPREF.setColumns(20);
        jTXTAREAPREF.setRows(5);
        jScrollPane2.setViewportView(jTXTAREAPREF);

        jTFCodPack.setText("jTextField2");

        jTFTotal.setText("jTextField3");

        jBtnNewdia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnNewdia.setForeground(new java.awt.Color(0, 0, 0));
        jBtnNewdia.setText("Nuevo Día Spa");

        jBtnGuardarDia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnGuardarDia.setForeground(new java.awt.Color(0, 0, 0));
        jBtnGuardarDia.setText("Guardar Cambios");

        jBtnEliminarDia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnEliminarDia.setForeground(new java.awt.Color(0, 0, 0));
        jBtnEliminarDia.setText("Elimiar Día");

        jBtnListarDias.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnListarDias.setForeground(new java.awt.Color(0, 0, 0));
        jBtnListarDias.setText("Listar Todo");

        jBtnVerSesiones.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnVerSesiones.setForeground(new java.awt.Color(0, 0, 0));
        jBtnVerSesiones.setText("Ver Sesión");

        jBtnActualizarTabla.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnActualizarTabla.setForeground(new java.awt.Color(0, 0, 0));
        jBtnActualizarTabla.setText("Actualizar Tabla");

        jBtnEliminarSesion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnEliminarSesion.setForeground(new java.awt.Color(0, 0, 0));
        jBtnEliminarSesion.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnNewdia)
                                .addGap(34, 34, 34)
                                .addComponent(jBtnGuardarDia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnVerSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jBtnActualizarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jBtnEliminarSesion))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLCliente)
                                        .addComponent(jLFecha)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLPrefe)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLCP))
                                        .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLTITULO)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLMonto)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFCodPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(229, 229, 229)
                                    .addComponent(jBtnEliminarDia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnListarDias))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 17, Short.MAX_VALUE))))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLSUBTITULO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLTITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCP)
                    .addComponent(jLFecha)
                    .addComponent(jTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCodPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCliente)
                    .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLMonto)
                                .addComponent(jTFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnNewdia)
                            .addComponent(jBtnGuardarDia)
                            .addComponent(jBtnEliminarDia)
                            .addComponent(jBtnListarDias)))
                    .addComponent(jLPrefe))
                .addGap(34, 34, 34)
                .addComponent(jLSUBTITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVerSesiones)
                    .addComponent(jBtnActualizarTabla)
                    .addComponent(jBtnEliminarSesion))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizarTabla;
    private javax.swing.JButton jBtnEliminarDia;
    private javax.swing.JButton jBtnEliminarSesion;
    private javax.swing.JButton jBtnGuardarDia;
    private javax.swing.JButton jBtnListarDias;
    private javax.swing.JButton jBtnNewdia;
    private javax.swing.JButton jBtnVerSesiones;
    private javax.swing.JComboBox<String> jCBCliente;
    private javax.swing.JLabel jLCP;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLMonto;
    private javax.swing.JLabel jLPrefe;
    private javax.swing.JLabel jLSUBTITULO;
    private javax.swing.JLabel jLTITULO;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCodPack;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFTotal;
    private javax.swing.JTextArea jTXTAREAPREF;
    private javax.swing.JTable jTableSesiones;
    // End of variables declaration//GEN-END:variables

}
