/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Cliente;
import Persistencia.ClienteData;
import Persistencia.Dia_De_SpaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import Modelo.Cliente;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Juan
 */
public class Dia_De_Spa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dia_De_Spa
     */
    public Dia_De_Spa() {
        initComponents();
        inicializarComboBox();
    }

    private void limpiarCampos() {
        jTFCodPack.setText("");
        jTFFecha.setText("");
        jTXTAREAPREF.setText("");
        jTFTotal.setText("");
        jCBCliente.setSelectedIndex(-1);
        jCBEstado.setSelectedIndex(-1);
    }

    private void inicializarComboBox() {
        // Cargar clientes
        ClienteData clienteData = new ClienteData();
        List<Cliente> listaClientes = clienteData.clientesActivos();
        jCBCliente.removeAllItems();
        for (Cliente c : listaClientes) {
            jCBCliente.addItem(c.getNombre_completo());
        }
        // Cargar estados posibles
        jCBEstado.removeAllItems();
        jCBEstado.addItem("Activo");
        jCBEstado.addItem("Cancelado");
        jCBEstado.addItem("Completado");
        jCBEstado.addItem("Pendiente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSesiones = new javax.swing.JTable();
        jLTITULO = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLCliente = new javax.swing.JLabel();
        jLPrefe = new javax.swing.JLabel();
        jLCP = new javax.swing.JLabel();
        jLMonto = new javax.swing.JLabel();
        jLSUBTITULO = new javax.swing.JLabel();
        jCBCliente = new javax.swing.JComboBox<>();
        jTFFecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTXTAREAPREF = new javax.swing.JTextArea();
        jTFCodPack = new javax.swing.JTextField();
        jTFTotal = new javax.swing.JTextField();
        jBtnNewdia = new javax.swing.JButton();
        jBtnGuardarDia = new javax.swing.JButton();
        jBtnEliminarDia = new javax.swing.JButton();
        jBtnListarDias = new javax.swing.JButton();
        jLestado = new javax.swing.JLabel();
        jCBEstado = new javax.swing.JComboBox<>();
        BtnBuscarCodPack = new javax.swing.JButton();

        jTableSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Hora Ini", "Hora Fin", "Masajista", "Consul.", "Tratam.", "Insta."
            }
        ));
        jScrollPane1.setViewportView(jTableSesiones);

        jLTITULO.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLTITULO.setForeground(new java.awt.Color(0, 0, 0));
        jLTITULO.setText("Gestion Día de Spa");

        jLFecha.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLFecha.setText("Fecha:");

        jLCliente.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLCliente.setText("Cliente:");

        jLPrefe.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLPrefe.setText("Preferencias:");

        jLCP.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLCP.setText("CodPack:");

        jLMonto.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLMonto.setText("Monto Total:");

        jLSUBTITULO.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLSUBTITULO.setForeground(new java.awt.Color(0, 0, 0));
        jLSUBTITULO.setText("Sesiones Vinculadas al Día de Spa");

        jCBCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTXTAREAPREF.setColumns(20);
        jTXTAREAPREF.setRows(5);
        jScrollPane2.setViewportView(jTXTAREAPREF);

        jTFCodPack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFCodPackMouseClicked(evt);
            }
        });
        jTFCodPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodPackActionPerformed(evt);
            }
        });

        jTFTotal.setText("$100");

        jBtnNewdia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnNewdia.setForeground(new java.awt.Color(0, 0, 0));
        jBtnNewdia.setText("Nuevo Día Spa");
        jBtnNewdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNewdiaActionPerformed(evt);
            }
        });

        jBtnGuardarDia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnGuardarDia.setForeground(new java.awt.Color(0, 0, 0));
        jBtnGuardarDia.setText("Guardar Cambios");
        jBtnGuardarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarDiaActionPerformed(evt);
            }
        });

        jBtnEliminarDia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnEliminarDia.setForeground(new java.awt.Color(0, 0, 0));
        jBtnEliminarDia.setText("Elimiar Día");

        jBtnListarDias.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnListarDias.setForeground(new java.awt.Color(0, 0, 0));
        jBtnListarDias.setText("Listar Todo");

        jLestado.setText("Estado:");

        jCBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BtnBuscarCodPack.setText("Buscar");
        BtnBuscarCodPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarCodPackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jBtnNewdia)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLSUBTITULO)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnGuardarDia)
                                .addGap(41, 41, 41)
                                .addComponent(jBtnEliminarDia)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnListarDias))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLMonto)
                        .addGap(18, 18, 18)
                        .addComponent(jTFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLestado)
                        .addGap(30, 30, 30)
                        .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLCliente)
                                            .addComponent(jLFecha)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLPrefe)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jLTITULO))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jCBCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTFFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(73, 73, 73)
                                        .addComponent(jLCP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTFCodPack, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(BtnBuscarCodPack))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLTITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFecha)
                    .addComponent(jTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCliente)
                            .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCP)
                            .addComponent(jTFCodPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPrefe)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLestado)
                                    .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLMonto)
                                    .addComponent(jTFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnNewdia)
                            .addComponent(jBtnGuardarDia)
                            .addComponent(jBtnEliminarDia)
                            .addComponent(jBtnListarDias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLSUBTITULO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(BtnBuscarCodPack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCodPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodPackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodPackActionPerformed

    private void jTFCodPackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFCodPackMouseClicked
        try {
            Dia_De_SpaData diaData = new Dia_De_SpaData();

            // Convertir el texto a entero
            int codPack;
            try {
                codPack = Integer.parseInt(jTFCodPack.getText());
            } catch (NumberFormatException e) {
                jTFCodPack.setText("");
                return; // si no es un número válido, salimos
            }

            Modelo.Dia_De_Spa dia = diaData.buscarDiaDeSpa(codPack);

            if (dia != null) {
                jTFCodPack.setText(String.valueOf(dia.getCodPack()));
                jTFFecha.setText(dia.getFechaHora().toString());
                jTXTAREAPREF.setText(dia.getPreferencias());
                jTFTotal.setText(String.valueOf(dia.getMonto()));
                jCBCliente.setSelectedItem(dia.getCliente().getNombre_completo());
            } else {
                // Si no encuentra nada, limpiamos campos
                jTFFecha.setText("");
                jTXTAREAPREF.setText("");
                jTFTotal.setText("");
                jCBCliente.setSelectedIndex(-1);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTFCodPackMouseClicked

    private void BtnBuscarCodPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarCodPackActionPerformed
        try {
            int codPack = Integer.parseInt(jTFCodPack.getText().trim());
            Dia_De_SpaData diaData = new Dia_De_SpaData();
            Modelo.Dia_De_Spa dia = diaData.buscarDiaDeSpa(codPack);

            if (dia != null) {
                jTFCodPack.setText(String.valueOf(dia.getCodPack()));
                jTFFecha.setText(dia.getFechaHora().toString());
                jTXTAREAPREF.setText(dia.getPreferencias());
                jTFTotal.setText(String.valueOf(dia.getMonto()));

                // Seleccionar cliente en el combo box
                jCBCliente.setSelectedItem(dia.getCliente().getNombre_completo());

                // Seleccionar estado
                jCBEstado.setSelectedItem(dia.getEstado());

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el Día de Spa con ese código.");
                limpiarCampos();

            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número válido en CodPack.");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BtnBuscarCodPackActionPerformed

    private void jBtnNewdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNewdiaActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jBtnNewdiaActionPerformed

    private void jBtnGuardarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarDiaActionPerformed
        
    }//GEN-LAST:event_jBtnGuardarDiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarCodPack;
    private javax.swing.JButton jBtnEliminarDia;
    private javax.swing.JButton jBtnGuardarDia;
    private javax.swing.JButton jBtnListarDias;
    private javax.swing.JButton jBtnNewdia;
    private javax.swing.JComboBox<String> jCBCliente;
    private javax.swing.JComboBox<String> jCBEstado;
    private javax.swing.JLabel jLCP;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLMonto;
    private javax.swing.JLabel jLPrefe;
    private javax.swing.JLabel jLSUBTITULO;
    private javax.swing.JLabel jLTITULO;
    private javax.swing.JLabel jLestado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCodPack;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFTotal;
    private javax.swing.JTextArea jTXTAREAPREF;
    private javax.swing.JTable jTableSesiones;
    // End of variables declaration//GEN-END:variables

}
