/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Heber Gomez PC
 */
public class Dia_de_Spa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dia_de_Spa
     */
    public Dia_de_Spa () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLcliente = new javax.swing.JLabel();
        jLPreference = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLhora = new javax.swing.JLabel();
        jLestado = new javax.swing.JLabel();
        jLMonto = new javax.swing.JLabel();
        jLSisDiaDeSpa = new javax.swing.JLabel();
        jLCodPack = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBtnAgregar = new javax.swing.JButton();
        jTextFieldCodPack = new javax.swing.JTextField();
        jCBClientes = new javax.swing.JComboBox<>();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextFieldMontoTOtal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBtnEliminar = new javax.swing.JButton();
        jBTnModificar = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLcliente.setText("Cliente:");
        getContentPane().add(jLcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 87, -1, -1));

        jLPreference.setText("Preferencias:");
        getContentPane().add(jLPreference, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLFecha.setText("Fecha:");
        getContentPane().add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLhora.setText("Hora:");
        getContentPane().add(jLhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLestado.setText("Estado:");
        getContentPane().add(jLestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jLMonto.setText("Monto Total:");
        getContentPane().add(jLMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLSisDiaDeSpa.setText("SISTEMA - DÍA DE SPA");
        getContentPane().add(jLSisDiaDeSpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 6, -1, -1));

        jLCodPack.setText("Código Paquete:");
        getContentPane().add(jLCodPack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N°", "Tratamiento", "Profesional", "Horario", "Instalación"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 488, 110));

        jLabel1.setText(" SESIONES DEL DÍA ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jBtnAgregar.setText("Agregar Sesión");
        getContentPane().add(jBtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jTextFieldCodPack.setText("noeditable");
        getContentPane().add(jTextFieldCodPack, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 42, -1, -1));

        jCBClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jCBClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 82, 84, -1));

        jTextFieldFecha.setText("Formtfecha");
        getContentPane().add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 81, -1));

        jTextFieldHora.setText("FormatHora");
        getContentPane().add(jTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 76, -1));

        jTextFieldMontoTOtal.setText("Noeditable");
        getContentPane().add(jTextFieldMontoTOtal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jBtnEliminar.setText("Eliminar Sesión");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jBTnModificar.setText("Modificar");
        getContentPane().add(jBTnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        jBtnGuardar.setText("Guardar");
        getContentPane().add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jBtnSalir.setText("Salir");
        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTnModificar;
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<String> jCBClientes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLCodPack;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLMonto;
    private javax.swing.JLabel jLPreference;
    private javax.swing.JLabel jLSisDiaDeSpa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLcliente;
    private javax.swing.JLabel jLestado;
    private javax.swing.JLabel jLhora;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCodPack;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldMontoTOtal;
    // End of variables declaration//GEN-END:variables
}
