/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Instalacion;
import Persistencia.InstalacionData;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Federico Galan
 */
public class DispoInstalaciones extends javax.swing.JInternalFrame {

    private InstalacionData instalacionData;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form DispoInstalaciones
     */
    public DispoInstalaciones() {
        initComponents();
        instalacionData = new InstalacionData();
        configurarTabla();
        configurarSpinners();
    }

    private void configurarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        String[] columnas = {"Código", "Nombre", "Detalle", "Precio 30min", "Estado"};
        modeloTabla.setColumnIdentifiers(columnas);
        jTableInstalaciones.setModel(modeloTabla);
    }
    
    private void configurarSpinners() {
        jSpinHours.setMinimum(0);
        jSpinHours.setMaximum(23);
        jSpinHours.setValue(12);
        
        jSpinMin.setMinimum(0);
        jSpinMin.setMaximum(59);
        jSpinMin.setValue(0);
    }
    
    private void buscarDisponibilidad() {
        try {
            if (jDateInstalaciones.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Seleccione una fecha.");
                return;
            }
            
            java.util.Date fechaSeleccionada = jDateInstalaciones.getDate();
            int hora = jSpinHours.getValue();
            int minutos = jSpinMin.getValue();
            
            LocalDateTime fechaHoraInicio = LocalDateTime.of(
                fechaSeleccionada.getYear() + 1900,
                fechaSeleccionada.getMonth() + 1,
                fechaSeleccionada.getDate(),
                hora, minutos
            );
            
            LocalDateTime fechaHoraFin = fechaHoraInicio.plusMinutes(30);
            
            Timestamp inicio = Timestamp.valueOf(fechaHoraInicio);
            Timestamp fin = Timestamp.valueOf(fechaHoraFin);
            
            List<Instalacion> instalacionesLibres = instalacionData.listarInstalacionesLibres(inicio, fin);
            
            modeloTabla.setRowCount(0);
            for (Instalacion inst : instalacionesLibres) {
                Object[] fila = {
                    inst.getCodInstal(),
                    inst.getNombre(),
                    inst.getDetalleUso(),
                    String.format("$%.2f", inst.getPrecio30m()),
                    inst.getEstado()
                };
                modeloTabla.addRow(fila);
            }
            
            if (instalacionesLibres.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "No hay instalaciones disponibles para la fecha y hora seleccionada.");
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Se encontraron " + instalacionesLibres.size() + " instalaciones disponibles.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar disponibilidad: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInstalaciones = new javax.swing.JTable();
        BtnBuscarDispo = new javax.swing.JButton();
        jDateInstalaciones = new com.toedter.calendar.JDateChooser();
        jSpinHours = new com.toedter.components.JSpinField();
        jSpinMin = new com.toedter.components.JSpinField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        Background.setBackground(new java.awt.Color(53, 30, 0));

        jTableInstalaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableInstalaciones);

        BtnBuscarDispo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        BtnBuscarDispo.setText("Buscar");
        BtnBuscarDispo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.red));
        BtnBuscarDispo.setBorderPainted(false);
        BtnBuscarDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarDispoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hora");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Minturos");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(BtnBuscarDispo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateInstalaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinHours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarDispo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarDispoActionPerformed
        // TODO add your handling code here:
        buscarDisponibilidad();
    }//GEN-LAST:event_BtnBuscarDispoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton BtnBuscarDispo;
    private com.toedter.calendar.JDateChooser jDateInstalaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinHours;
    private com.toedter.components.JSpinField jSpinMin;
    private javax.swing.JTable jTableInstalaciones;
    // End of variables declaration//GEN-END:variables
}
