/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Masajista;
import Modelo.TipoDeTratamiento;
import Persistencia.MasajistaData;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Heber Gomez PC
 */
public class MasajistaModificarBuscar extends javax.swing.JInternalFrame {

    /**
     * Creates new form MasajistaModificarBuscar
     */
    public MasajistaModificarBuscar () {
        initComponents();
        imagenFondo();
        visualfondo();
        cargarEspecialidades();
        cargarEstados();
    }
    private void buscarMasajista () {
        try {
            int matricula = Integer.parseInt(jTextFieldMatricula.getText());
            MasajistaData data = new MasajistaData();
//             Guardar resultado de la busqueda
            Masajista m = data.buscarMasajistaPorId(matricula);
            if (m == null) {
                JOptionPane.showMessageDialog(this,
                    "No se encontro el masajista.");
                return;
            }
//              Cargar campos
            jTextFieldNomYApe.setText(m.getNombreYapellido());
            jTextFieldTelefono.setText(m.getTelefono());
            jComboBoxEspecialidad.setSelectedItem(m.getEspecialidad());
            jComboBoxEstado.setSelectedItem(m.getEstado());
        }
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "La matricula debe ser un numero.");
        }
    }

private void modificarMasajista() {
    try {
        int matricula = Integer.parseInt(jTextFieldMatricula.getText());
        MasajistaData data = new MasajistaData();

//          Buscar masajista original
        Masajista m = data.buscarMasajistaPorId(matricula);
        if (m == null) {
            JOptionPane.showMessageDialog(this, "No se encontro el masajista.");
            return;
        }

//          Tomar valores del formulario
        String nombre = jTextFieldNomYApe.getText().trim();
        String telefono = jTextFieldTelefono.getText().trim();

//          Validaciones
        if (!nombre.matches("[a-zA-Z ]+")) {
            JOptionPane.showMessageDialog(this,
                "El nombre solo puede contener letras y espacios.");
            return;
        }

        if (!telefono.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,
                "El telefono solo puede contener numeros.");
            return;
        }

//          Actualizar objeto masajista
        m.setNombreYapellido(nombre);
        m.setTelefono(telefono);
        m.setEspecialidad(jComboBoxEspecialidad.getSelectedItem().toString());
        m.setEstado(jComboBoxEstado.getSelectedItem().toString());

//          Guardar cambios
        data.modificarMasajista(m);

        JOptionPane.showMessageDialog(this, "Masajista modificado con exito.");

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "La matricula debe ser un numero.");
    }
}


    private void cargarEspecialidades () {
        // Limpia primero
        jComboBoxEspecialidad.removeAllItems();
        for (TipoDeTratamiento tipo : TipoDeTratamiento.values()) {
            jComboBoxEspecialidad.addItem(tipo.name());
        }
    }

    private void cargarEstados () {
        jComboBoxEstado.removeAllItems();
        jComboBoxEstado.addItem("ACTIVO");
        jComboBoxEstado.addItem("INACTIVO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelNomYApe = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jComboBoxEspecialidad = new javax.swing.JComboBox<>();
        jTextFieldNomYApe = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelEspecialidad = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jButtonAtras = new javax.swing.JButton();
        jComboBoxEstado = new javax.swing.JComboBox<>();

        setClosable(true);

        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificado.png"))); // NOI18N
        jLabel7.setText("Modificar Masajista");
        jLabel7.setAlignmentX(0.5F);
        jLabel7.setFocusable(false);
        jLabel7.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefono-movil.png"))); // NOI18N
        jLabel3.setText("Telefono");
        jLabel3.setOpaque(true);

        jLabelEstado.setBackground(new java.awt.Color(204, 204, 204));
        jLabelEstado.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estado.png"))); // NOI18N
        jLabelEstado.setText("Estado");
        jLabelEstado.setOpaque(true);

        jLabelNomYApe.setBackground(new java.awt.Color(204, 204, 204));
        jLabelNomYApe.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabelNomYApe.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomYApe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jLabelNomYApe.setText("Nombre y Apellido");
        jLabelNomYApe.setOpaque(true);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonModificar.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar-el-archivo.png"))); // NOI18N
        jButtonModificar.setText("Guardar Cambios");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jComboBoxEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEspecialidadActionPerformed(evt);
            }
        });

        jLabelEspecialidad.setBackground(new java.awt.Color(204, 204, 204));
        jLabelEspecialidad.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabelEspecialidad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/experto.png"))); // NOI18N
        jLabelEspecialidad.setText("Especialidad");
        jLabelEspecialidad.setOpaque(true);

        jLabelMatricula.setBackground(new java.awt.Color(204, 204, 204));
        jLabelMatricula.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabelMatricula.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carne-de-identidad.png"))); // NOI18N
        jLabelMatricula.setText("Matricula");
        jLabelMatricula.setOpaque(true);

        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelEspecialidad)
                                    .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonModificar)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNomYApe)
                                    .addComponent(jLabelMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNomYApe, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMatricula)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomYApe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomYApe))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAtras, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstado))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificar)))
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEspecialidadActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscarMasajista();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        modificarMasajista();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBoxEspecialidad;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEspecialidad;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNomYApe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNomYApe;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
 private void visualfondo () {
        // Reemplazamos el content pane
        setContentPane(jDesktopPane1);
        // Layout para que el panel se vea
        jDesktopPane1.setLayout(new java.awt.BorderLayout(HEIGHT, WIDTH));
        // Panel visible sobre el fondo
        jPanel1.setOpaque(false);
        jPanel1.setVisible(true);
        // Limpiamos y agregamos
        jDesktopPane1.removeAll();
        jDesktopPane1.add(jPanel1, java.awt.BorderLayout.CENTER);
        jDesktopPane1.repaint();
    }

    private void imagenFondo () {
        // Fondo 
        jDesktopPane1 = new javax.swing.JDesktopPane() {
            @Override
            protected void paintComponent (Graphics g) {
                super.paintComponent(g);
                Image img = new ImageIcon(getClass().
                    getResource("/img/ModificarMasajista.png")).
                    getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
    }
}
