/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author Heber Gomez PC
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        imagenFondo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1Sesion = new javax.swing.JMenu();
        jMenuItemDiaDeSpa = new javax.swing.JMenuItem();
        jMenuItemSesion = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        insertarYmodCliente = new javax.swing.JMenuItem();
        btnConsultorio = new javax.swing.JMenu();
        jMenu4Instalaciones = new javax.swing.JMenu();
        JmenuInstalaciones = new javax.swing.JMenuItem();
        jMenu5Masajista = new javax.swing.JMenu();
        jMenuItemRegistroAlta = new javax.swing.JMenuItem();
        jMenuItemModificarBuscar = new javax.swing.JMenuItem();
        jMenuItemAltaBajaLogica = new javax.swing.JMenuItem();
        jMenuItemListarConsultar = new javax.swing.JMenuItem();
        jMenu6Producto = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Escritorio.setEnabled(false);
        Escritorio.setMaximumSize(new java.awt.Dimension(1024, 1024));
        Escritorio.setMinimumSize(new java.awt.Dimension(490, 490));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1137, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGap(0, 531, Short.MAX_VALUE)
=======
            .addGap(0, 559, Short.MAX_VALUE)
>>>>>>> 30c22becfdb8649d2480b9e150007fe2cc3b51bc
        );

        jMenu1Sesion.setText("Sesion");

        jMenuItemDiaDeSpa.setText("Dia de Spa");
        jMenuItemDiaDeSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDiaDeSpaActionPerformed(evt);
            }
        });
        jMenu1Sesion.add(jMenuItemDiaDeSpa);

        jMenuItemSesion.setText("Buscar ");
        jMenuItemSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSesionActionPerformed(evt);
            }
        });
        jMenu1Sesion.add(jMenuItemSesion);

        jMenuBar1.add(jMenu1Sesion);

        jMenuCliente.setText("Cliente");

        insertarYmodCliente.setText("Registro y Modificacion de Clientes");
        insertarYmodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarYmodClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(insertarYmodCliente);

        jMenuBar1.add(jMenuCliente);

        btnConsultorio.setText("Consultorio");
        btnConsultorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultorioMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnConsultorio);

        jMenu4Instalaciones.setText("Instalaciones");

        JmenuInstalaciones.setText("Instalaciones");
        JmenuInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuInstalacionesActionPerformed(evt);
            }
        });
        jMenu4Instalaciones.add(JmenuInstalaciones);

        jMenuBar1.add(jMenu4Instalaciones);

        jMenu5Masajista.setText("Gestion de Masajista");

        jMenuItemRegistroAlta.setText("Registro / Alta");
        jMenuItemRegistroAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroAltaActionPerformed(evt);
            }
        });
        jMenu5Masajista.add(jMenuItemRegistroAlta);

        jMenuItemModificarBuscar.setText("Modificar / Buscar");
        jMenuItemModificarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarBuscarActionPerformed(evt);
            }
        });
        jMenu5Masajista.add(jMenuItemModificarBuscar);

        jMenuItemAltaBajaLogica.setText("Alta / Baja logica");
        jMenuItemAltaBajaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaBajaLogicaActionPerformed(evt);
            }
        });
        jMenu5Masajista.add(jMenuItemAltaBajaLogica);

        jMenuItemListarConsultar.setText("Listar / Consultar");
        jMenuItemListarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarConsultarActionPerformed(evt);
            }
        });
        jMenu5Masajista.add(jMenuItemListarConsultar);

        jMenuBar1.add(jMenu5Masajista);

        jMenu6Producto.setText("Tratamiento");
        jMenu6Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ProductoActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Registro/Alta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6Producto.add(jMenuItem1);

        jMenuItem2.setText("Modificar / Buscar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6Producto.add(jMenuItem2);

        jMenuItem3.setText("Alta / Baja logica");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6Producto.add(jMenuItem3);

        jMenuItem4.setText("Listar / Consultar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6Producto.add(jMenuItem4);

        jMenuBar1.add(jMenu6Producto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSesionActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        Dia_de_Spa insertModClient = new Dia_de_Spa();
        insertModClient.setVisible(true);
        Escritorio.add(insertModClient);
        Escritorio.moveToFront(insertModClient);
        int x = (Escritorio.getWidth() - insertModClient.getWidth()) / 2;
        int y = (Escritorio.getHeight() - insertModClient.getHeight()) / 2;
        insertModClient.setLocation(x, y);
    }//GEN-LAST:event_jMenuItemSesionActionPerformed

    private void insertarYmodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarYmodClienteActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        Cliente insertModClient = new Cliente();
        insertModClient.setVisible(true);
        Escritorio.add(insertModClient);
        Escritorio.moveToFront(insertModClient);
        int x = (Escritorio.getWidth() - insertModClient.getWidth()) / 2;
        int y = (Escritorio.getHeight() - insertModClient.getHeight()) / 2;
        insertModClient.setLocation(x, y);
    }//GEN-LAST:event_insertarYmodClienteActionPerformed

    private void jMenuInstalacionesVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInstalacionesVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuInstalacionesVerActionPerformed

    private void jMenuItemRegistroAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroAltaActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        MasajistaRegistroAlta am = new MasajistaRegistroAlta();
        am.setVisible(true);
        Escritorio.add(am);
        Escritorio.moveToFront(am);
        // con esto van a centrar la ventana que crearon
        int x = (Escritorio.getWidth() - am.getWidth()) / 2;
        int y = (Escritorio.getHeight() - am.getHeight()) / 2;
        am.setLocation(x, y);
    }//GEN-LAST:event_jMenuItemRegistroAltaActionPerformed

    private void jMenuItemModificarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarBuscarActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        MasajistaModificarBuscar am = new MasajistaModificarBuscar();
        am.setVisible(true);
        Escritorio.add(am);
        Escritorio.moveToFront(am);
        // con esto van a centrar la ventana que crearon
        int x = (Escritorio.getWidth() - am.getWidth()) / 2;
        int y = (Escritorio.getHeight() - am.getHeight()) / 2;
        am.setLocation(x, y);
    }//GEN-LAST:event_jMenuItemModificarBuscarActionPerformed

    private void jMenuItemAltaBajaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaBajaLogicaActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        MasajistaAltaBajaLogica am = new MasajistaAltaBajaLogica();
        am.setVisible(true);
        Escritorio.add(am);
        Escritorio.moveToFront(am);
        // con esto van a centrar la ventana que crearon
        int x = (Escritorio.getWidth() - am.getWidth()) / 2;
        int y = (Escritorio.getHeight() - am.getHeight()) / 2;
        am.setLocation(x, y);
    }//GEN-LAST:event_jMenuItemAltaBajaLogicaActionPerformed

    private void jMenuItemListarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarConsultarActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        MasajistaListarConsultar am = new MasajistaListarConsultar();
        am.setVisible(true);
        Escritorio.add(am);
        Escritorio.moveToFront(am);
        // con esto van a centrar la ventana que crearon
        int x = (Escritorio.getWidth() - am.getWidth()) / 2;
        int y = (Escritorio.getHeight() - am.getHeight()) / 2;
        am.setLocation(x, y);
    }//GEN-LAST:event_jMenuItemListarConsultarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        TratamientoRegistroAlta am = new TratamientoRegistroAlta();
        am.setVisible(true);
        Escritorio.add(am);
        Escritorio.moveToFront(am);
        // con esto van a centrar la ventana que crearon
        int x = (Escritorio.getWidth() - am.getWidth()) / 2;
        int y = (Escritorio.getHeight() - am.getHeight()) / 2;
        am.setLocation(x, y);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu6ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ProductoActionPerformed

    }//GEN-LAST:event_jMenu6ProductoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        TratamientoModificarBuscar am = new TratamientoModificarBuscar();
        am.setVisible(true);
        Escritorio.add(am);
        Escritorio.moveToFront(am);
        // con esto van a centrar la ventana que crearon
        int x = (Escritorio.getWidth() - am.getWidth()) / 2;
        int y = (Escritorio.getHeight() - am.getHeight()) / 2;
        am.setLocation(x, y);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        TratamientoAltaBajaLogica am = new TratamientoAltaBajaLogica();
        am.setVisible(true);
        Escritorio.add(am);
        Escritorio.moveToFront(am);
        // con esto van a centrar la ventana que crearon
        int x = (Escritorio.getWidth() - am.getWidth()) / 2;
        int y = (Escritorio.getHeight() - am.getHeight()) / 2;
        am.setLocation(x, y);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        TratamientoListarConsultar am = new TratamientoListarConsultar();
        am.setVisible(true);
        Escritorio.add(am);
        Escritorio.moveToFront(am);
        // con esto van a centrar la ventana que crearon
        int x = (Escritorio.getWidth() - am.getWidth()) / 2;
        int y = (Escritorio.getHeight() - am.getHeight()) / 2;
        am.setLocation(x, y);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnConsultorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultorioMouseClicked
        // TODO add your handling code here:
        VistaConsultorio vc = new VistaConsultorio();
        Escritorio.add(vc);
        vc.setVisible(true);
    }//GEN-LAST:event_btnConsultorioMouseClicked

    private void jMenuItemDiaDeSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDiaDeSpaActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();

        Dia_de_Spa vistaSpa = new Dia_de_Spa();
        vistaSpa.setVisible(true);
        Escritorio.add(vistaSpa);
        Escritorio.moveToFront(vistaSpa);

        // Centrar la vista dentro del escritorio
        int x = (Escritorio.getWidth() - vistaSpa.getWidth()) / 2;
        int y = (Escritorio.getHeight() - vistaSpa.getHeight()) / 2;
        vistaSpa.setLocation(x, y);
    }//GEN-LAST:event_jMenuItemDiaDeSpaActionPerformed

    private void JmenuInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuInstalacionesActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();

        Instalacion Insta = new Instalacion();
        Insta.setVisible(true);
        Escritorio.add(Insta);
        Escritorio.moveToFront(Insta);

        // Centrar la vista dentro del escritorio
        int x = (Escritorio.getWidth() - Insta.getWidth()) / 2;
        int y = (Escritorio.getHeight() - Insta.getHeight()) / 2;
        Insta.setLocation(x, y);
        
    }//GEN-LAST:event_JmenuInstalacionesActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu btnConsultorio;
    private javax.swing.JMenuItem JmenuInstalaciones;
    private javax.swing.JMenuItem insertarYmodCliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu1Sesion;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu4Instalaciones;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu5Masajista;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu6Producto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAltaBajaLogica;
    private javax.swing.JMenuItem jMenuItemDiaDeSpa;
    private javax.swing.JMenuItem jMenuItemListarConsultar;
    private javax.swing.JMenuItem jMenuItemModificarBuscar;
    private javax.swing.JMenuItem jMenuItemRegistroAlta;
    private javax.swing.JMenuItem jMenuItemSesion;
    // End of variables declaration//GEN-END:variables
  private void imagenFondo() {
        Escritorio = new JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon icon = new ImageIcon(getClass().
                        getResource(
                                "/img/SpaEntreDedos.png"));
                g.
                        drawImage(icon.getImage(), 0, 0, getWidth(), getHeight(),
                                this);
            }
        };
        this.setContentPane(Escritorio);
    }
}
