/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author Heber Gomez PC
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal () {
        initComponents();
        imagenFondo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1Sesion = new javax.swing.JMenu();
        jMenuItemDiaDeSpa = new javax.swing.JMenuItem();
        jMenuItemSesion = new javax.swing.JMenuItem();
        jMenu2Cliente = new javax.swing.JMenu();
        jMenu3Consultorio = new javax.swing.JMenu();
        jMenu4Instalaciones = new javax.swing.JMenu();
        jMenu5Masajista = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6Producto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1Sesion.setText("Sesion");

        jMenuItemDiaDeSpa.setText("Dia de Spa");
        jMenu1Sesion.add(jMenuItemDiaDeSpa);

        jMenuItemSesion.setText("Buscar ");
        jMenuItemSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSesionActionPerformed(evt);
            }
        });
        jMenu1Sesion.add(jMenuItemSesion);

        jMenuBar1.add(jMenu1Sesion);

        jMenu2Cliente.setText("Cliente");
        jMenuBar1.add(jMenu2Cliente);

        jMenu3Consultorio.setText("Consultorio");
        jMenuBar1.add(jMenu3Consultorio);

        jMenu4Instalaciones.setText("Instalaciones");
        jMenuBar1.add(jMenu4Instalaciones);

        jMenu5Masajista.setText("Masajista");

        jMenuItem1.setText("Agregar masajista");
        jMenu5Masajista.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu5Masajista.add(jMenuItem2);

        jMenuBar1.add(jMenu5Masajista);

        jMenu6Producto.setText("Tratamiento");
        jMenuBar1.add(jMenu6Producto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run () {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1Sesion;
    private javax.swing.JMenu jMenu2Cliente;
    private javax.swing.JMenu jMenu3Consultorio;
    private javax.swing.JMenu jMenu4Instalaciones;
    private javax.swing.JMenu jMenu5Masajista;
    private javax.swing.JMenu jMenu6Producto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemDiaDeSpa;
    private javax.swing.JMenuItem jMenuItemSesion;
    // End of variables declaration//GEN-END:variables
  private void imagenFondo () {
        jDesktopPane1 = new JDesktopPane() {
            @Override
            protected void paintComponent (Graphics g) {
                super.paintComponent(g);
                ImageIcon icon = new ImageIcon(getClass().
                    getResource(
                        "/img/SpaEntreDedos.png"));
                g.
                    drawImage(icon.getImage(), 0, 0, getWidth(), getHeight(),
                        this);
            }
        };
        this.setContentPane(jDesktopPane1);
    }
}
