/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Cliente;
import Modelo.Dia_De_Spa;
import Persistencia.ClienteData;
import Persistencia.Dia_De_SpaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import Modelo.Sesion;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class vistaDiaDeSpa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dia_De_Spa
     */
    public vistaDiaDeSpa() {
        initComponents();
        inicializarComboBox();
        jTFTotal.setEditable(true);
    }

    private void limpiarCampos() {
        jTFCodPack.setText("");
        jTFFecha.setText("");
        jTXTAREAPREF.setText("");
        jTFTotal.setText("");
        jCBCliente.setSelectedIndex(-1);
        jCBEstado.setSelectedIndex(-1);
    }

    private void mostrarSesiones(List<Sesion> sesiones) {
        // Crear modelo de tabla
        DefaultTableModel modelo = new DefaultTableModel();

        // Columnas
        modelo.addColumn("Hora Ini");
        modelo.addColumn("Hora Fin");
        modelo.addColumn("Masajista");
        modelo.addColumn("Consultorio");
        modelo.addColumn("Tratam.");
        modelo.addColumn("Insta.");

        // Llenar filas
        for (Sesion s : sesiones) {
            Object[] fila = {
                s.getFechaHoraInicio(), // Hora Ini
                s.getFechaHoraFin(), // Hora Fin
                s.getMasajista() != null ? s.getMasajista().getNombreYapellido() : "", // Masajista
                s.getConsultorio() != null ? s.getConsultorio().getNroConsultorio() : "", // Consultorio
                s.getTratamiento() != null ? s.getTratamiento().getNombre() : "", // Tratamiento
                s.getInstalacion() != null ? s.getInstalacion().getNombre() : "" // Instalación
            };
            modelo.addRow(fila);
        }

        // Asignar modelo a la tabla
        jTableSesiones.setModel(modelo);
    }

    private void inicializarComboBox() {
        // Cargar clientes
        ClienteData clienteData = new ClienteData();
        List<Cliente> listaClientes = clienteData.clientesActivos();

        jCBCliente.removeAllItems();
        for (Cliente c : listaClientes) {
            // MOSTRAR: "id - nombre"
            jCBCliente.addItem(c.getCodCli() + " - " + c.getNombre_completo());
        }
        jCBCliente.setSelectedIndex(-1);

        // Cargar estados posibles
        jCBEstado.removeAllItems();
        jCBEstado.addItem("pendiente");
        jCBEstado.addItem("confirmado");
        jCBEstado.addItem("realizado");
        jCBEstado.addItem("cancelado");
    }

    private void mostrarSoloEsteDia(Modelo.Dia_De_Spa dia) {

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("CodPack");
        modelo.addColumn("Fecha");
        modelo.addColumn("Cliente");
        modelo.addColumn("Monto");
        modelo.addColumn("Estado");

        Object[] fila = {
            dia.getCodPack(),
            dia.getFechaHora().toString(),
            dia.getCliente().getNombre_completo(),
            dia.getMonto(),
            dia.getEstado()
        };

        modelo.addRow(fila);

        jTableSesiones.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSesiones = new javax.swing.JTable();
        jLTITULO = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLCliente = new javax.swing.JLabel();
        jLPrefe = new javax.swing.JLabel();
        jLCP = new javax.swing.JLabel();
        jLMonto = new javax.swing.JLabel();
        jLSUBTITULO = new javax.swing.JLabel();
        jCBCliente = new javax.swing.JComboBox<>();
        jTFFecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTXTAREAPREF = new javax.swing.JTextArea();
        jTFCodPack = new javax.swing.JTextField();
        jTFTotal = new javax.swing.JTextField();
        jBtnEliminarDia = new javax.swing.JButton();
        jBtnListarDias = new javax.swing.JButton();
        jLestado = new javax.swing.JLabel();
        jCBEstado = new javax.swing.JComboBox<>();
        BtnBuscarCodPack = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnCrearDia = new javax.swing.JButton();

        jTableSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Hora Ini", "Hora Fin", "Masajista", "Consul.", "Tratam.", "Insta."
            }
        ));
        jScrollPane1.setViewportView(jTableSesiones);

        jLTITULO.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLTITULO.setForeground(new java.awt.Color(0, 0, 0));
        jLTITULO.setText("Gestion Día de Spa");

        jLFecha.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLFecha.setText("Fecha:");

        jLCliente.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLCliente.setText("Cliente:");

        jLPrefe.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLPrefe.setText("Preferencias:");

        jLCP.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLCP.setText("CodPack:");

        jLMonto.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLMonto.setText("Monto Total:");

        jLSUBTITULO.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLSUBTITULO.setForeground(new java.awt.Color(0, 0, 0));
        jLSUBTITULO.setText("Sesiones Vinculadas al Día de Spa");

        jCBCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTXTAREAPREF.setColumns(20);
        jTXTAREAPREF.setRows(5);
        jScrollPane2.setViewportView(jTXTAREAPREF);

        jTFCodPack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFCodPackMouseClicked(evt);
            }
        });
        jTFCodPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodPackActionPerformed(evt);
            }
        });

        jTFTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTotalActionPerformed(evt);
            }
        });

        jBtnEliminarDia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnEliminarDia.setForeground(new java.awt.Color(0, 0, 0));
        jBtnEliminarDia.setText("Elimiar Día");
        jBtnEliminarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarDiaActionPerformed(evt);
            }
        });

        jBtnListarDias.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtnListarDias.setForeground(new java.awt.Color(0, 0, 0));
        jBtnListarDias.setText("Listar Todo");
        jBtnListarDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListarDiasActionPerformed(evt);
            }
        });

        jLestado.setText("Estado:");

        jCBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BtnBuscarCodPack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe_78956.png"))); // NOI18N
        BtnBuscarCodPack.setText("Buscar");
        BtnBuscarCodPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarCodPackActionPerformed(evt);
            }
        });

        BtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar_93493.png"))); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        BtnCrearDia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnCrearDia.setForeground(new java.awt.Color(0, 0, 0));
        BtnCrearDia.setText("Crear Dia");
        BtnCrearDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLCliente)
                                            .addComponent(jLFecha)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLPrefe)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jLTITULO))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jCBCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTFFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(73, 73, 73)
                                        .addComponent(jLCP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTFCodPack, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(BtnBuscarCodPack))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(BtnCrearDia, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnEliminarDia)
                                    .addComponent(jLSUBTITULO))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnListarDias)
                                .addGap(54, 54, 54)
                                .addComponent(BtnActualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLMonto)
                                .addGap(18, 18, 18)
                                .addComponent(jTFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLestado)
                                .addGap(30, 30, 30)
                                .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLTITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFecha)
                    .addComponent(jTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCliente)
                            .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCP)
                            .addComponent(jTFCodPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPrefe)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLestado)
                                    .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLMonto)
                                    .addComponent(jTFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnEliminarDia)
                            .addComponent(jBtnListarDias)
                            .addComponent(BtnActualizar)
                            .addComponent(BtnCrearDia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLSUBTITULO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(BtnBuscarCodPack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCodPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodPackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodPackActionPerformed

    private void jTFCodPackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFCodPackMouseClicked
        try {
            Dia_De_SpaData diaData = new Dia_De_SpaData();

            // Convertir el texto a entero
            int codPack;
            try {
                codPack = Integer.parseInt(jTFCodPack.getText());
            } catch (NumberFormatException e) {
                jTFCodPack.setText("");
                return; // si no es un número válido, salimos
            }

            Modelo.Dia_De_Spa dia = diaData.buscarDiaDeSpa(codPack);

            if (dia != null) {
                jTFCodPack.setText(String.valueOf(dia.getCodPack()));
                jTFFecha.setText(dia.getFechaHora().toString());
                jTXTAREAPREF.setText(dia.getPreferencias());
                jTFTotal.setText(String.valueOf(dia.getMonto()));
                jCBCliente.setSelectedItem(dia.getCliente().getNombre_completo());
            } else {
                // Si no encuentra nada, limpiamos campos
                jTFFecha.setText("");
                jTXTAREAPREF.setText("");
                jTFTotal.setText("");
                jCBCliente.setSelectedIndex(-1);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTFCodPackMouseClicked

    private void BtnBuscarCodPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarCodPackActionPerformed
        try {
            int codPack = Integer.parseInt(jTFCodPack.getText().trim());
            Dia_De_SpaData diaData = new Dia_De_SpaData();
            Modelo.Dia_De_Spa dia = diaData.buscarDiaDeSpa(codPack);

            if (dia != null) {
                jTFCodPack.setText(String.valueOf(dia.getCodPack()));
                jTFFecha.setText(dia.getFechaHora().toString());
                jTXTAREAPREF.setText(dia.getPreferencias());
                jTFTotal.setText(String.valueOf(dia.getMonto()));

                // Seleccionar cliente en el combo
                String itemCliente = dia.getCliente().getCodCli()
                        + " - " + dia.getCliente().getNombre_completo();
                jCBCliente.setSelectedItem(itemCliente);


                // Seleccionar estado
                jCBEstado.setSelectedItem(dia.getEstado());

                // Cargar sesiones en la tabla
                mostrarSesiones(dia.getSesiones());
                //️ AQUI se actualiza la tabla principal con SOLO este día
                mostrarSoloEsteDia(dia);

            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se encontró el Día de Spa con ese código.");
                limpiarCampos();
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese un número válido en CodPack.");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BtnBuscarCodPackActionPerformed

    private void jBtnListarDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListarDiasActionPerformed
        try {
            Dia_De_SpaData diaData = new Dia_De_SpaData();
            List<Modelo.Dia_De_Spa> dias = diaData.listarDiasDeSpa();

            // Crear modelo para la tabla
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("CodPack");
            modelo.addColumn("Fecha");
            modelo.addColumn("Cliente");
            modelo.addColumn("Monto");
            modelo.addColumn("Estado");

            for (Modelo.Dia_De_Spa dia : dias) {
                Object[] fila = {
                    dia.getCodPack(),
                    dia.getFechaHora().toString(),
                    dia.getCliente().getNombre_completo(),
                    dia.getMonto(),
                    dia.getEstado()
                };
                modelo.addRow(fila);
            }

            jTableSesiones.setModel(modelo);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al listar los días de spa.");
        }
    }//GEN-LAST:event_jBtnListarDiasActionPerformed

    private void jBtnEliminarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarDiaActionPerformed
        try {
            int codPack = Integer.parseInt(jTFCodPack.getText().trim());

            // Confirmación antes de eliminar
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿ESTÁS SEGURO QUE QUIERES ELIMINAR este Día de Spa y todas sus sesiones?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (respuesta == JOptionPane.YES_OPTION) {
                Dia_De_SpaData diaData = new Dia_De_SpaData();

                // Primero eliminamos las sesiones vinculadas al día
                boolean sesionesEliminadas = diaData.eliminarSesionesPorDia(codPack);

                // Después eliminamos el día de spa
                boolean eliminado = diaData.eliminarDiaDeSpa(codPack);

                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Día de Spa y sus sesiones eliminados correctamente.");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró el Día de Spa a eliminar.");
                }
            } // Si el usuario elige NO, no hace nada

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido en CodPack.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage());
        }
    }//GEN-LAST:event_jBtnEliminarDiaActionPerformed

    private void jTFTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTotalActionPerformed

    }//GEN-LAST:event_jTFTotalActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        try {
            int codPack = Integer.parseInt(jTFCodPack.getText().trim());
            String nuevoEstado = jCBEstado.getSelectedItem().toString().trim().toLowerCase();
            String nuevasPreferencias = jTXTAREAPREF.getText().trim();

            Dia_De_SpaData diaData = new Dia_De_SpaData();
            boolean actualizado = diaData.actualizarEstadoYPreferencias(codPack, nuevoEstado, nuevasPreferencias);

            if (actualizado) {
                JOptionPane.showMessageDialog(this, "Día de Spa actualizado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el Día de Spa a actualizar.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido en CodPack.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage());
        }
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnCrearDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearDiaActionPerformed
            try {
        //Validar selección de cliente
        if (jCBCliente.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente.");
            return;
        }

        //  Validar fecha
        if (jTFFecha.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la fecha del día de spa.");
            return;
        }

        // Crear objeto Dia_De_Spa y asignar fecha
        Dia_De_Spa dia = new Dia_De_Spa();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm");
        dia.setFechaHora(LocalDateTime.parse(jTFFecha.getText(), formatter));

        //Asignar preferencias y estado
        dia.setPreferencias(jTXTAREAPREF.getText());
        dia.setEstado(jCBEstado.getSelectedItem().toString());

        //Leer y validar monto (precio)
        double monto = 0;
        try {
            if (!jTFTotal.getText().trim().isEmpty()) {
                monto = Double.parseDouble(jTFTotal.getText().trim());
                if (monto < 0) {
                    JOptionPane.showMessageDialog(this, "El monto no puede ser negativo.");
                    return;
                }
            }
<<<<<<< HEAD
            dia.setMonto(monto);

            // CLIENTE
            ClienteData cData = new ClienteData();
            String sel = jCBCliente.getSelectedItem().toString();
            int codCli = Integer.parseInt(sel.split(" - ")[0]);
            Cliente cli = cData.buscarClientePorId(codCli);
            dia.setCliente(cli);

            // GUARDAR
            Dia_De_SpaData diaData = new Dia_De_SpaData();
            int codPack = diaData.guardarDiaDeSpa(dia);

            jTFCodPack.setText(String.valueOf(codPack));
            jTFTotal.setText(String.valueOf(monto));
            JOptionPane.showMessageDialog(this, "Día de Spa creado. Código: " + codPack);

            BtnCrearDia.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear el Día de Spa: " + e.getMessage());
=======
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido para el monto.");
            return;
>>>>>>> 90a139e51e6bdb722265583c4a1cb5137995f9a3
        }
        dia.setMonto(monto);

        //Asignar cliente al día
        ClienteData cData = new ClienteData();
        String sel = jCBCliente.getSelectedItem().toString();
        int codCli = Integer.parseInt(sel.split(" - ")[0]);
        Cliente cli = cData.buscarClientePorId(codCli);
        dia.setCliente(cli);

        //Guardar el día de spa en la base
        Dia_De_SpaData diaData = new Dia_De_SpaData();
        int codPack = diaData.guardarDiaDeSpa(dia);

        jTFCodPack.setText(String.valueOf(codPack));
        JOptionPane.showMessageDialog(this, "Día de Spa creado. Código: " + codPack);

        // Habilitar botón crear
        BtnCrearDia.setEnabled(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al crear el Día de Spa: " + e.getMessage());
    }
    }//GEN-LAST:event_BtnCrearDiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnBuscarCodPack;
    private javax.swing.JButton BtnCrearDia;
    private javax.swing.JButton jBtnEliminarDia;
    private javax.swing.JButton jBtnListarDias;
    private javax.swing.JComboBox<String> jCBCliente;
    private javax.swing.JComboBox<String> jCBEstado;
    private javax.swing.JLabel jLCP;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLMonto;
    private javax.swing.JLabel jLPrefe;
    private javax.swing.JLabel jLSUBTITULO;
    private javax.swing.JLabel jLTITULO;
    private javax.swing.JLabel jLestado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCodPack;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFTotal;
    private javax.swing.JTextArea jTXTAREAPREF;
    private javax.swing.JTable jTableSesiones;
    // End of variables declaration//GEN-END:variables

}
