package Vistas;

import Modelo.Consultorio;
import Persistencia.ConsultorioData;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nehuen Zerdá
 */
public class VistaConsultorio extends javax.swing.JInternalFrame {
    
    private final ConsultorioData consultorioData = new ConsultorioData();
private DefaultTableModel modelo;


    /**
     * Creates new form Consultorio
     */
    public VistaConsultorio () {
        initComponents();
        
        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/img/lupa.png"));
Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
btnBuscar.setIcon(new ImageIcon(imagenEscalada));

// Ruta: la imagen debe estar en src/img/...
ImageIcon ico = new ImageIcon(getClass().getResource("/img/spa.png"));
// ajustá el tamaño a gusto
int w = 48, h = 48;
Image img = ico.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
lblLogo.setIcon(new ImageIcon(img));
lblLogo.setText(null); // por si acaso

        setClosable(true);
setIconifiable(true);
setMaximizable(true);
setResizable(true);
setTitle("Consultorio");

txtNro.setEnabled(false); // PK autoincrement

cargarCombos();
prepararTabla();
cargarTabla();

    }
    
    private void cargarCombos() {
    cboUsos.removeAllItems();
    cboUsos.addItem("Facial");
    cboUsos.addItem("Corporal");
    cboUsos.addItem("Relajacion");
    cboUsos.addItem("Estetico");

    cboApto.removeAllItems();
    cboApto.addItem("Si");
    cboApto.addItem("No");
}

private void prepararTabla() {
    modelo = new DefaultTableModel(new Object[]{"Nro","Usos","Apto","Equipamiento"}, 0){
        @Override public boolean isCellEditable(int r,int c){ return false; }
    };
    tblConsultorios.setModel(modelo);
    tblConsultorios.setRowHeight(22);
    
}

private void cargarTabla() {
    modelo.setRowCount(0);
    List<Consultorio> lista = consultorioData.listarConsultorios();
    for (Consultorio c : lista) {
        modelo.addRow(new Object[]{
            c.getNroConsultorio(), c.getUsos(), c.getApto(), c.getEquipamiento()
        });
    }
}

private void limpiarCampos() {
    txtNro.setText("");
    cboUsos.setSelectedIndex(0);
    cboApto.setSelectedIndex(0);
    txtEquip.setText("");
    txtBuscar.setText("");
    tblConsultorios.clearSelection();
}

private Consultorio leerFormulario() {
    Consultorio c = new Consultorio();
    if (!txtNro.getText().isBlank()) {
        c.setNroConsultorio(Integer.parseInt(txtNro.getText().trim()));
    }
    c.setUsos((String)cboUsos.getSelectedItem());
    c.setApto((String)cboApto.getSelectedItem());
    c.setEquipamiento(txtEquip.getText().trim());
    return c;
}

private void pasarFilaAFormulario() {
    int row = tblConsultorios.getSelectedRow();
    if (row >= 0) {
        txtNro.setText(String.valueOf(modelo.getValueAt(row, 0)));
        cboUsos.setSelectedItem(modelo.getValueAt(row, 1));
        cboApto.setSelectedItem(modelo.getValueAt(row, 2));
        txtEquip.setText(String.valueOf(modelo.getValueAt(row, 3)));
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNro = new javax.swing.JLabel();
        lblUsos = new javax.swing.JLabel();
        cboUsos = new javax.swing.JComboBox<>();
        lblApto = new javax.swing.JLabel();
        cboApto = new javax.swing.JComboBox<>();
        lblEquip = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEquip = new javax.swing.JTextArea();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultorios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        txtNro = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();

        lblNro.setText("N°:");

        lblUsos.setText("Usos:");

        cboUsos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblApto.setText("Apto:");

        cboApto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblEquip.setText("Equipamiento:");

        txtEquip.setColumns(20);
        txtEquip.setLineWrap(true);
        txtEquip.setRows(5);
        txtEquip.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtEquip);

        lblBuscar.setText("Buscar por ID:");

        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblConsultorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro", "Usos", "Apto", "Equipamiento"
            }
        ));
        tblConsultorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsultoriosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblConsultorios);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUsos)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboUsos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBuscar)
                                .addGap(37, 37, 37)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEquip)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblApto)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGuardar)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNro)
                                .addComponent(lblBuscar)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsos)
                            .addComponent(cboUsos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApto)
                            .addComponent(cboApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(lblEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnEliminar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    cboUsos.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
        Consultorio c = leerFormulario();
        if (c.getUsos()==null || c.getApto()==null) {
            JOptionPane.showMessageDialog(this, "Completa Usos y Apto.");
            return;
        }
        consultorioData.guardarConsultorio(c);
        cargarTabla();
        if (c.getNroConsultorio() > 0) {
            txtNro.setText(String.valueOf(c.getNroConsultorio()));
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if (txtNro.getText().isBlank()) {
        JOptionPane.showMessageDialog(this, "Selecciona un registro de la tabla.");
        return;
    }
    Consultorio c = leerFormulario();
    consultorioData.actualizarConsultorio(c);
    cargarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (txtNro.getText().isBlank()) {
        JOptionPane.showMessageDialog(this, "Selecciona un registro.");
        return;
    }
    int nro = Integer.parseInt(txtNro.getText());
    int ok = JOptionPane.showConfirmDialog(this,
        "¿Eliminar consultorio Nº " + nro + "?", "Confirmacion",
        JOptionPane.YES_NO_OPTION);
    if (ok == JOptionPane.YES_OPTION) {
        consultorioData.eliminarConsultorio(nro);
        cargarTabla();
        limpiarCampos();
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String q = txtBuscar.getText().trim();
    if (q.isBlank()) { cargarTabla(); return; }

    try {
        int nro = Integer.parseInt(q);
        var c = consultorioData.buscarConsultorio(nro);
        modelo.setRowCount(0);
        if (c != null) {
            modelo.addRow(new Object[]{
                c.getNroConsultorio(), c.getUsos(), c.getApto(), c.getEquipamiento()
            });
        } else {
            JOptionPane.showMessageDialog(this, "No encontrado.");
        }
    } catch (NumberFormatException e) {
        // Filtro por 'usos'
        cargarTabla();
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            String usos = String.valueOf(modelo.getValueAt(i, 1));
            if (!usos.toLowerCase().contains(q.toLowerCase())) {
                modelo.removeRow(i);
            }
        }
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    cargarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tblConsultoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultoriosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
        pasarFilaAFormulario();
    }
    }//GEN-LAST:event_tblConsultoriosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboApto;
    private javax.swing.JComboBox<String> cboUsos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApto;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblEquip;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNro;
    private javax.swing.JLabel lblUsos;
    private javax.swing.JTable tblConsultorios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtEquip;
    private javax.swing.JTextField txtNro;
    // End of variables declaration//GEN-END:variables
}
