/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vistas;

import Persistencia.ClienteData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Carreño Lucas
 */
public class VtnaEmergCliente extends javax.swing.JDialog {

    /**
     * Creates new form VtnaEmergCliente
     */
    private int idCliente;
    private boolean modRealizada = false; 

    public VtnaEmergCliente(java.awt.Frame parent, boolean modal, int idCliente) {
        super(parent, modal);
        this.idCliente = idCliente;
        initComponents();
        this.setLocationRelativeTo(parent);
    }
    
    private int getidCliente() {
        return this.idCliente;
    }

    public boolean modExitosa() {
        return modRealizada;
    }
    
    private List<String> checkBoxSeleccionados() {
        List<String> seleccion = new ArrayList<>();
        if (jCBxApellidoNombre.isSelected()) seleccion.add("Apellido y Nombre");
        if (jCBxDni.isSelected()) seleccion.add("DNI");
        if (jCBxTelefono.isSelected()) seleccion.add("Telefono");
        if (jCBxEdad.isSelected()) seleccion.add("Edad");
        if (jCBxAfecciones.isSelected()) seleccion.add("Afecciones");
        return seleccion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBxApellidoNombre = new javax.swing.JCheckBox();
        jCBxDni = new javax.swing.JCheckBox();
        jCBxTelefono = new javax.swing.JCheckBox();
        jCBxEdad = new javax.swing.JCheckBox();
        jCBxAfecciones = new javax.swing.JCheckBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tituloSeleccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana de Modificaciones");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jCBxApellidoNombre.setText("Apellido y Nombre");

        jCBxDni.setText("DNI");

        jCBxTelefono.setText("Telefono");

        jCBxEdad.setText("Edad");

        jCBxAfecciones.setText("Afecciones");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tituloSeleccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tituloSeleccion.setText("Seleccione el/los datos a modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCBxApellidoNombre)
                                .addComponent(jCBxDni, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBxTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBxEdad, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBxAfecciones)
                                .addGap(18, 18, 18)
                                .addComponent(btnAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(tituloSeleccion)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloSeleccion)
                .addGap(13, 13, 13)
                .addComponent(jCBxApellidoNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCBxDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBxTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBxEdad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBxAfecciones)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnCancelar))
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        int clienteSeleccionado = getidCliente();
        List<String> camposSeleccionados = checkBoxSeleccionados();
        if (camposSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un campo para modificarlo.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
    
        ClienteData clien = new ClienteData();
        boolean mensajeFinal = true;

        for (String datoSeleccionado : camposSeleccionados) {
            String valorSinEspacios = "";
            boolean validacion = false;
            while (!validacion) { 
                String nuevoValor = null;
                String valorModificado = "<html>Ingrese el nuevo valor de : <b>" + datoSeleccionado + "</b></html>";
                nuevoValor = JOptionPane.showInputDialog(this, valorModificado, "Modificar al cliente con ID : " + clienteSeleccionado, JOptionPane.QUESTION_MESSAGE);
                if (nuevoValor == null) {
                    mensajeFinal = false; 
                    validacion = true;
                    break;
                }

                valorSinEspacios = nuevoValor.trim();
            
                String mensajeError = "";
                boolean errorValidacion = false;

                if (valorSinEspacios.isEmpty()) {
                    mensajeError = "El campo ' " + datoSeleccionado + " ' no puede estar vacio.";
                    errorValidacion = true;
                }
                else if (datoSeleccionado.equals("Apellido y Nombre")) {
                    if (!valorSinEspacios.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$")) {
                        mensajeError = "Solo puede tener letras y espacios.";
                        errorValidacion = true;
                    }
                    else if (valorSinEspacios.length() < 8) {
                        mensajeError = "Debe tener un minimo de 8 caracteres.";
                        errorValidacion = true;
                    }
                }
                else if (datoSeleccionado.equals("Telefono")) {
                    int caracteres = valorSinEspacios.length();
                    if (!valorSinEspacios.matches("^[0-9+]+$")) {
                        mensajeError = "Solo puede ingresar numeros y '+' (ejemplo: +5492664495032)";
                        errorValidacion = true;
                    } 
                    else if (caracteres < 10 || caracteres > 15) {
                        mensajeError = "El numero de telefono debe tener entre 10 y 15 caracteres.";
                        errorValidacion = true;
                    }
                }
                else if (datoSeleccionado.equals("DNI")) {
                    try {
                        int dni = Integer.parseInt(valorSinEspacios);
                        if (dni < 6000000) {
                            mensajeError = "El DNI debe ser un numero entero de 7 cifras (minimo '6.000.000').";
                            errorValidacion = true;
                        }
                    } catch (NumberFormatException e) {
                        mensajeError = "El DNI debe contener solo numeros enteros.";
                        errorValidacion = true;
                    }
                }
                else if (datoSeleccionado.equals("Edad")) {
                    try {
                        int edad = Integer.parseInt(valorSinEspacios);
                        if (edad <= 5 || edad > 100) {
                            mensajeError = "La Edad debe estar en un rango de (6 a 100 años).";
                            errorValidacion = true;
                        }
                    } catch (NumberFormatException e) {
                        mensajeError = "Deben ser solo numeros enteros.";
                        errorValidacion = true;
                    }
                }
                else if (datoSeleccionado.equals("Afecciones")) {
                    if (!valorSinEspacios.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$")) {
                        mensajeError = "Solo puede tener letras y espacios.";
                        errorValidacion = true;
                    }
                    else if (valorSinEspacios.length() < 4) {
                        mensajeError = "Debe tener un minimo de 4 caracteres.";
                        errorValidacion = true;
                    }
                }
                if (errorValidacion) {
                    JOptionPane.showMessageDialog(this, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    validacion = true;
                }
            }
            if (!mensajeFinal) {
                break;
            }
            if (validacion) {
                boolean exitoActualizacion = clien.actualizarCampo(clienteSeleccionado, datoSeleccionado, valorSinEspacios);
                if (!exitoActualizacion) {
                    mensajeFinal = false;
                    JOptionPane.showMessageDialog(this, "Error al actualizar el campo ' " + datoSeleccionado + " '.", "FATAL ERROR", JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }
        }
        if (mensajeFinal) {
            JOptionPane.showMessageDialog(this, "La modificacion ha sido completada.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            modRealizada = true;
            this.dispose();
        } else if (mensajeFinal == false){
            this.dispose();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        modRealizada = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox jCBxAfecciones;
    private javax.swing.JCheckBox jCBxApellidoNombre;
    private javax.swing.JCheckBox jCBxDni;
    private javax.swing.JCheckBox jCBxEdad;
    private javax.swing.JCheckBox jCBxTelefono;
    private javax.swing.JLabel tituloSeleccion;
    // End of variables declaration//GEN-END:variables
}
